### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jijishthomas** [greybax/cordova-plugin-proguard#11]
Hello,
 I have added this plugin to my ionic project. After building the app, the source code still looks same! What all should I need to add proguard-custom.txt inorder to obfuscate all js files in my project?

**Comment by greybax** [comment]
This extension doesn't do any with obfuscation, minimization, etc. This is part of job for proguard. Please see their api on official website https://www.guardsquare.com/en/products/proguard/manual
