### ISSUE TITLE
Add com.android.vending.billing

### ISSUE THREAD

**Issue by Gerarddus** [greybax/cordova-plugin-proguard#16]
I think it might be a good idea to add something like:

```-keep class com.android.vending.billing.** { *; }```

to the proguard-custom.txt.
Because obfuscation is probably used when the app has subscriptions/inapppurchases etc.
Maybe there's a way of making it optional when installing the plugin?

**Comment by greybax** [comment]
@Gerarddus make sense! Let's add it. Will you prepare PR? :)

**Comment by greybax** [comment]
Related PR #17
