### ISSUE TITLE
Attempt to invoke virtual method 'android.content.res.XmlResourcePars android.content.pm.Providerinfo.loadXmlMetaData(android.content.pm java.lang. String)' on a null object reference

### ISSUE THREAD

**Issue by swanand6300** [greybax/cordova-plugin-proguard#18]
I have successfully installed proguard plugin but when i generate signed APK my Camera is not working and throwing error "**Attempt to invoke virtual method 'android.content.res.XmlResourcePars
android.content.pm.Providerinfo.loadXmlMetaData(android.content.pm
java.lang. String)' on a null object reference**"

**Comment by greybax** [comment]
Did you try to add 
```
-keep class android.content.res.XmlResourcePars
-keep class android.content.pm.Providerinfo.loadXmlMetaData
```
into `proguard-custom.txt` ?

**Comment by jsphivee** [comment]
Hi @greybax, I tried adding that but still camera won't work. I added it here:

_# Enable proguard with Cordova
-keep class org.apache.cordova.** { *; }
-keep public class * extends org.apache.cordova.CordovaPlugin
**-keep class android.content.res.XmlResourcePars
-keep class android.content.pm.Providerinfo.loadXmlMetaData**

#END_
