### ISSUE TITLE
when i add custom rules it's not coming  

### ISSUE THREAD

**Issue by sparavindans** [greybax/cordova-plugin-proguard#6]
when i add custom rules  under plugin->cordova-plugin-proguard ->proguard-custom.txt but the changes not available under->platforms->android->app->src->proguard-custom.txt . 

kindly lets us know where i have to add more rules in cordova project

**Comment by greybax** [comment]
@sparavindans seems seems that you try to find `proguard-custom.txt` in wrong place. It should be in `assets/www/proguard-custom.txt` for Cordova version <7.0 and here `src/main/assets/www/proguard-custom.txt` for cordova 7.0 (if you will use https://github.com/SujitSingh/cordova-plugin-proguard fork)

**Comment by greybax** [comment]
is it issue still actual? if not will close it

**Comment by Hanzofm** [comment]
Hi, wich is the project absolute path where I have to place my proguard-custom.txt on:
-cordova android 6.4.0 
-Cordova 8

thanks

**Comment by greybax** [comment]
@Hanzofm It should be in assets/www/proguard-custom.txt for Cordova version <7.0 and here src/main/assets/www/proguard-custom.txt for cordova 7.0 as it was mention above.

**Comment by NadaMustafa** [comment]
you should remove and re-add Android platform after changing plugin->cordova-plugin-proguard ->proguard-custom.txt

**Comment by alaagamalkhattab** [comment]
> you should remove and re-add Android platform after changing `plugins/cordova-plugin-proguard /proguard-custom.txt `
> 
> ```
> ionic cordova platform rm android
> ionic cordova platform add android
> ```

yo save my life nada ..thank you

**Comment by engymamdou7** [comment]
> you should remove and re-add Android platform after changing `plugins/cordova-plugin-proguard /proguard-custom.txt `
> 
> ```
> ionic cordova platform rm android
> ionic cordova platform add android
> ```

it works with me thank you so much nada

**Comment by greybax** [comment]
updated `README.md` file accordingly with @NadaMustafa remarks
